"""Add user roles and audit log

Revision ID: 97957cfa27e7
Revises: d1c31f7092f3
Create Date: 2024-12-10 20:36:55.245073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97957cfa27e7'
down_revision: Union[str, None] = 'd1c31f7092f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
