"""Add price column to Item model

Revision ID: d1c31f7092f3
Revises: dd3ed1c7db08
Create Date: 2024-12-09 18:46:33.875254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1c31f7092f3'
down_revision: Union[str, None] = 'dd3ed1c7db08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
